apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-allow-only-lb
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector: {} # Autorise le trafic venant d'ArgoCD ou du LoadBalancer
    ports:
    - protocol: TCP
      port: 3000
